### ISSUE TITLE
PERPIXEL_TRANSLUCENT translucency is not supported

### ISSUE THREAD

**Issue by piotrhoppe** [Chris2011/NbScratchFile#23]
This error occur for me when I work remotely by VNC
And when I run the NetBeans I see this:
```
Init Webview stuff.
ES2 Prism: Error - reported GLX version = 1.2
    GLX version 1.3 or higher is required
```
Call stack
```
java.lang.UnsupportedOperationException: PERPIXEL_TRANSLUCENT translucency is not supported
	at java.desktop/java.awt.Window.setBackground(Window.java:3878)
	at java.desktop/java.awt.Dialog.setBackground(Dialog.java:1330)
	at org.chrisle.netbeans.plugins.utils.WebViewDialog.init(WebViewDialog.java:49)
	at org.chrisle.netbeans.plugins.nbscratchfile.Installer.run(Installer.java:22)
[catch] at org.netbeans.core.windows.WindowManagerImpl$Exclusive$1.run(WindowManagerImpl.java:1615)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by piotrhoppe** [comment]
My solution for this: https://github.com/Chris2011/NbScratchFile/pull/24

**Comment by Chris2011** [comment]
I had problems whily building, updated my node dependencies, will merge and release it today.

**Comment by piotrhoppe** [comment]
Great and many thanks

**Comment by Chris2011** [comment]
Will not happen in version 2.0.0 anymore, due to removing HTML4J and went back to good old swing.
